spring:
  application:
    name: wishlist

  datasource:
    url: jdbc:mysql://localhost:3306/wishlist_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true

server:
  port: 8080
